on: [push]

jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Baseline Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@fix/PA-13914-qa # GET Latest Version from https://github.com/marketplace/actions/soos-dast
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "GH Actions - DAST Simple"
          target_url: "https://joaquinalvarez.dev/"
          api_url: "https://qa-api.soos.io/api/"
          auth_login_url: "https://joaquinalvarez.dev/"
          auth_username: "franco"
          auth_password: "Password1!"
          verbose: true
         

