on: [push]

jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Baseline Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v1.2.7 # GET Latest Version from https://github.com/marketplace/actions/soos-dast
        with:

          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: 'GH Actions - DAST simple'          
          target_url: 'https://joaquinalvarez.dev/'
          api_url: 'https://api.soos.io/api/'          
          auth_login_url: 'https://joaquinalvarez.dev/'             

