on: [push]

jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Baseline Analysis 
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v2.0.9 # GET Latest Version from https://github.com/marketplace/actions/soos-dast
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "GH Actions - DAST Simple v2.0.9"
          scan_mode: "baseline"
          target_url: "https://demoqa.com/profile"
          api_url: 'https://qa-api.soos.io/api/'
          image_tag: latest
          log_level: debug
          on_failure: continue_on_failure
          auth_form_type: "simple"
          #auth_verification_url: https://demoqa.com/Account/v1/User/fbe86d3e-3cd0-4d0c-a13c-d1b19f08644d
          auth_username: "franco"
          auth_password: "Temporal1234!"
          auth_username_field: username
          auth_password_field: password
          auth_submit_field: login
          auth_login_URL: https://demoqa.com/login
         

