on: [push]

jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Baseline Analysis 
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@644117da443899e887013e779539c99b66c7015e #GET Latest Version from https://github.com/marketplace/actions/soos-dast
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          image_tag: beta          
          project_name: "GH Actions - DAST Simple" 
          scan_mode: "baseline" 
          #api_scan_format: "GraphQL"
          target_url: "https://joaquinalvarez.dev/" 
          #target_url: "https://demoqa.com/profile"
          api_url: 'https://qa-api.soos.io/api/'
          #on_failure: fail_the_build
          log_level: INFO
          #output_format: NONE
          #other_options: -d
          #auth_form_type: "simple"
          #auth_verification_url: https://demoqa.com/Account/v1/User/fbe86d3e-3cd0-4d0c-a13c-d1b19f08644d
          #auth_verification_url: https://demoqa\.com/Account/(.*)
          #auth_username: "franco"
          #auth_password: "Temporal1234!"
          #auth_username_field: username
          #auth_password_field: password
          #auth_submit_field: login 
          #auth_login_URL: https://demoqa.com/login
          verbose: true
          request_cookies: "cookie1:a,cookie2:b"
          #checkoutDir: ""
          #debug: true
          

          
          

