on: [push]

jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Baseline Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v2.0.6 # GET Latest Version from https://github.com/marketplace/actions/soos-dast
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "GH Actions - DAST Simple API"
          scan_mode: "baseline"
          target_url: "https://joaquinalvarez.dev/"
          api_url: 'https://qa-api.soos.io/api/'
          request_headers: "additionalHeader:test,additionalHeader2:test2"
          request_cookies: "cookie1:a,cookie2:b"
          bearer_token: "invalidValue"
          log_level: "DEBUG"
          verbose: true
          
         

