on: [push]

jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Baseline Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@v2.0.6 # GET Latest Version from https://github.com/marketplace/actions/soos-dast
        with:
          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: "GH Actions - DAST Simple"
          scan_mode: "baseline"
          target_url: "https://demoqa.com/profile"
          api_url: 'https://api.soos.io/api/'
          verbose: true
          auth_form_type: "simple"
          auth_verification_url: https://demoqa\.com/Account/(.*)
          auth_username: "franco"
          auth_password: "!"
          auth_login_url: "https://demoqa.com/login"
         

